name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 17 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with JDK ${{ matrix.java }} and Maven ${{ env.M2_HOME }}
        run: mvn --batch-mode --update-snapshots verify